version: '2'
services:
  krypton-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/krypton/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=krypton
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
